import './styles/global.css';

export const metadata = {
  title: 'Welcome to argon',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <div className="min-h-screen bg-background">
          <div className="mx-auto max-w-[1366px] px-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
