import { SidebarProvider, SidebarTrigger } from '@argon/shared/ui-components';
import './styles/global.css';
import { SidebarFeature } from '@argon/shell/sidebar-feature';

export const metadata = {
  title: 'Welcome to argon',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <SidebarFeature />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
