import { Header } from '@argon/ui-header-ui';
import { NavbarAdmin } from '@argon/ui-navbar-ui';

export const metadata = {
  title: 'Welcome to argon',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <NavbarAdmin />
      <main>{children}</main>
    </>
  );
}
